add solutions for 04-SPA 01, 02, 03, 04, 05 and 06
js-tasks-ru/vue-20201022_luchemete-otake pull request #6
Opened 2020-11-17 16:02 UTC by LuchemeteOtake

2020-11-17 17:12 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-17 18:29 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при са��мите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
+ Значение параметров должно соответствовать значениям query параметров в маршруте
+ При изменении значения параметров должен меняться маршрут (push или query)
+ При переходе на маршрут с другим query, должно обновлять соответствующие параметры
+ Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
```
```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```
```diff
ContentTabs
+ ContentTabs должен иметь обязатель��ый параметр список tabs
+ ContentTabs должен рендерить список вкладок
+ Активная вкладка должна иметь класс content-tabs__tab_active
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-11-17 19:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-17 23:13 UTC, ShGKme requested changes
В задаче ContentTabs требуется обернуть слот в оригинальный `div`.
В задаче AuthPages страницы обновляются при сабмите формы...
Остальные задачи приняты.

2020-11-17 23:13 UTC, ShGKme commented on 04-SPA/01-ContentTabs/components/ContentTabs.vue
> +    <slot></slot>
Обёртка с content-tabs__content здесь была нужна

2020-11-17 23:13 UTC, ShGKme commented on 04-SPA/06-Query/views/PageWithQuery.vue
> +  },
Вместо добавления функции в хук `created` лучше добавить параметр `immediate: true` в соответствующий `watch`, тогда его обработчик будет вызван сразу.

2020-11-18 19:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-18 20:04 UTC, ShGKme approved these changes
Все задачи приняты 👍

2020-11-18 20:06 UTC, ShGKme approved these changes

2020-11-18 20:07 UTC, merged